### ISSUE TITLE
Blank page in V3.5

### ISSUE THREAD

**Issue by sucrepop** [philippd1/bludit-auto-update#2]
I installed the plugin for the V 3.71 
i'm in V 3.5
https://www.sucrepop.com
when I activate the plugin i'm on a blank page
there are no parameters available

**Comment by philippdormann** [comment]
Hey!
Thanks for using my plugin.
Not sure if I got your point correctly.
The plugin itself currently doesn't have a normal configuration screen like many other plugins.
When you open the plugin, it automatically updates Bludit to the newest version:wink:

**Comment by sucrepop** [comment]
Hi
Thanks for your answer
As there is a parameters page, I thought there was something to do

So I clicked on activate and ?
I’m still on V3.5


Did I miss Something ?

Provenance : Courrier pour Windows 10

De : Philipp Dormann
Envoyé le :mardi 29 janvier 2019 15:44
À : philippd1/bludit-auto-update
Cc : sucrepop; Author
Objet :Re: [philippd1/bludit-auto-update] Blank page in V3.5 (#2)

Hey!
Thanks for using my plugin.
Not sure if I got your point correctly.
The plugin itself currently doesn't have a normal configuration screen like many other plugins.
When you open the plugin, it automatically updates Bludit to the newest version😉

**Comment by philippdormann** [comment]
I checked this issue with a clean installation of Bludit 3.5.0.
installed the bludit-auto-update plugin.
Clicked on "activate", the update worked as expected... also, when clicking on "settings" it still works...

**Comment by sucrepop** [comment]
Thanks for the answer  
so I guess it's by my side  
  
i'll try on my other website [https://lucy-racquel-and-me.com/](https://lucy-racquel-and-me.com/)  but since he's on the same host ...  
  
anyway, thanks for the plugin  
Phil

**Comment by philippdormann** [comment]
be sure to shoot me a message if you can get any reproducable errors.
For the time being, I'll close this issue.
