### ISSUE TITLE
Partially succesful upgrade however multiple issues with approach

### ISSUE THREAD

**Issue by BlakesHeaven** [philippd1/bludit-auto-update#3]
I was on Bludit 3.9.2, uploaded the plugin and activated it.
**Immediatly** after activating the plugin I got the following:
 > Warning: rmdir(./auto-updater-temp//bludit-3-10-0): Directory not empty in /customers/a/f/3/uwcc.uk/httpd.www/practice/bl-plugins/bludit-auto-update/auto_update.php on line 107
 > 
 > Warning: rmdir(./auto-updater-temp/): Directory not empty in /customers/a/f/3/uwcc.uk/httpd.www/practice/bl-plugins/bludit-auto-update/auto_update.php on line 107
 > 
 > **Bludit was updated to 'bludit-3-10-0'**.
 > This plugin automatically downloads and installs the latest Bludit version offered on the official  > Bludit site.
 > Warning: This will overwrite your bludit installation.

I can confirm that the folder `auto-updater-temp` has been created and that it contains the latest current version (v3.10.0).
![image](https://user-images.githubusercontent.com/37149377/67334036-75bfc380-f519-11e9-8b54-2329e5b8e1dc.png)
The only file it contains is a .htaccess file. It is otherwise empty.

I can also confirm that I can see new functionality in admin and the about admin confirms the new version.
 > ![image](https://user-images.githubusercontent.com/37149377/67338374-e28a8c00-f520-11e9-9c23-696045b16b4f.png)

The first point is that when the plugin is de-active, the only option is to click on `Activate` and the following highlighted text is irrelevant:
 > ![image](https://user-images.githubusercontent.com/37149377/67335034-05b23d00-f51b-11e9-9977-8104ec453bfe.png)

Having subsequently entered `Settings` again I get a clean page, however, the warning, "_**Warning**: This will overwrite your bludit installation._" is a bit late in the day and a moot point, or it that pointless... _Sorry, excuse me, I don't mean to be facetious._

 > ![image](https://user-images.githubusercontent.com/37149377/67336857-f254a100-f51d-11e9-9708-0287419b9ac8.png)

**First Issue:** The plugin should not upgrade anything on just activating it.

**Second Issue:** Maybe a debatable point, but one I feel strongly about, is that clicking on `Settings` should not trigger an upgrade.
We should end up on a screen that at least displays the current version, the expected upgrade version and some very clear instructions about what is going to happen covering stuff like "Try first in DEV" and "Have you taken a full backup?". 
Then after some simple text box confirmation that the user types in, eg `bludit-3-10-0`, are they allowed to click an `Upgrade Now` button.

**Third Issue:** The temp folder still exists - it should be cleaned up. Not much more to be said on that other than maybe offer the clean up as an option in settings. After all, one may wish to download and check the files used for the upgrade.

**Fourth Issue:** None of the Plugins or themes seem to have been upgraded. At least not according to their version number:
 > ![image](https://user-images.githubusercontent.com/37149377/67337741-88d59200-f51f-11e9-9b0c-32ed16d5076b.png)

**Fifth Issue:** After downloading the latest release from bludit and running a compare, as i would when doing a manual upgrade, I can't see that any of the files have been upgraded... at least not by date. I admit that this is very strange because I can see new functionality, eg the custom fields.
 > ![image](https://user-images.githubusercontent.com/37149377/67338929-12865f00-f522-11e9-8cd6-134ecdeeafb0.png)

**Closing comment:**
I am really sorry to blast in like this; I am actually very impressed and with the new functionally doubtless added, it was a lot simpler than manually downloading and then uploading and checking everything.

Once the above issues are resolved I'll be very pleased to use this on a live site.

Then, as an enhancement, it would be good to see a list of the files that are going to be replaced/deleted by the upgrade.

**Comment by philippdormann** [comment]
Hi @BlakesHeaven 

thanks for taking your time to describe your experience using the plugin.

I fully agree with your point that the plugin should not upgrade anything on just activating it nor when clicking on "Settings" - I just haven't found a proper way to do so when I built the plugin.

a disclaimer/ warning "Have you taken a full backup?" along with a confirmation box would be good, too.

On why the temp folder still exists: well, I actually don't know right now...😅

> Fourth Issue: None of the Plugins or themes seem to have been upgraded. At least not according to their version number:

yeah, of course not. the plugin is only intended for upgrading the bludit core itself.
that's where my repos https://github.com/philippd1/plugin-download and https://github.com/philippd1/theme-download come in. these two should be able to upgrade the plugins/ themes.

unfortunately, I cannot actively develop this plugin at the moment as I am very timely constrained :/
I would appreciate pull requests at any time of course!
Thanks 🙂

**Comment by BlakesHeaven** [comment]
Thanks for the responce. I know all about time constraints 🙂

Just a quick thought, if there existed a config called `Active`, that defaults to false and then only run the update if the Admin sets it to true.  At least that way it can be activated without it running.
Don't hurry on my account though 😎

**Comment by philippdormann** [comment]
hey @BlakesHeaven 

since the features `Auto Updates`, `Plugins installer` and `Themes installer` are on the roadmap for Bludit v4 (https://github.com/bludit/bludit/issues/1057) I'm considering dropping support for these plugins all together 😐

**Comment by BlakesHeaven** [comment]
Hey, thanks so much for letting  me know your thoughts, and I understand.  
I'd be proud that your idea made it into the core product, well done 👍

**Comment by philippdormann** [comment]
yeah, I mean of course it's cool that the idea for the plugins. I just don't think that the bludit repo itself is correct for this as it is a little to conservative in terms of development freedom imho. (in direct comparison to a standalone plugin)

Actually, I'm using Bludit in a current project - maybe I'll give working on my plugins another shot🙂 let's see, I will keep you updated ;)

**Comment by philippdormann** [comment]
Hey @BlakesHeaven I actually had some free time today and decided to work on this again with a fresh mind 🙂
all logic happens in the background, page load is instant and much more :)
here's some screenshots on the current progress:

**plugin page**
![image](https://user-images.githubusercontent.com/17651032/74615777-ec657a00-5123-11ea-9ffb-4349a0000d40.png)

**update in progress**
![image](https://user-images.githubusercontent.com/17651032/74615799-15860a80-5124-11ea-8779-c02a6fb14e03.png)

**update done**
![image](https://user-images.githubusercontent.com/17651032/74615790-08691b80-5124-11ea-8f01-efc3077f861f.png)

## and yes, it actually works awesome and really fast 🔥🔥
might be releasing this tomorrow or the day after, enough for today tho ^^ (already 1:25 here in Germany 🙄)

**Comment by BlakesHeaven** [comment]
Good on you...that looks really very good.
Well done .

**Comment by philippdormann** [comment]
so yeah, that's it 😎
be sure to let me know your thoughts of the new release.
I will absolutely trust it - even in production :)
